In [1]:
import numpy as np

In [2]:
arr = np.arange(12).reshape((3,4))

In [3]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
arr_con1 = np.concatenate([arr, arr], axis=1)

In [5]:
arr_con1

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [6]:
arr_con2 = np.concatenate([arr, arr])

In [7]:
arr_con2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
import pandas as pd

In [9]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])

In [10]:
df1

a         b         c         d
0  0.804507 -0.750605 -1.689265  0.055414
1 -0.788530 -2.092272  0.153200 -1.433101
2 -0.283484 -0.718330  1.049392 -0.035094

In [11]:
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [12]:
df2

b         d         a
0 -0.892189  0.510108 -0.819327
1 -1.110872  0.611648 -0.825834

In [13]:
arr_con3 = pd.concat([df1, df2], ignore_index=True)

In [14]:
arr_con3

a         b         c         d
0  0.804507 -0.750605 -1.689265  0.055414
1 -0.788530 -2.092272  0.153200 -1.433101
2 -0.283484 -0.718330  1.049392 -0.035094
3 -0.819327 -0.892189       NaN  0.510108
4 -0.825834 -1.110872       NaN  0.611648

In [15]:
arr_con4 = pd.concat([df1, df2])

In [16]:
arr_con4

a         b         c         d
0  0.804507 -0.750605 -1.689265  0.055414
1 -0.788530 -2.092272  0.153200 -1.433101
2 -0.283484 -0.718330  1.049392 -0.035094
0 -0.819327 -0.892189       NaN  0.510108
1 -0.825834 -1.110872       NaN  0.611648